
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package front_end.parser;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int ENTER = 10;
  public static final int DIFERENT = 26;
  public static final int SI = 31;
  public static final int RESERVA = 37;
  public static final int RESTA = 3;
  public static final int EParen = 6;
  public static final int OLO = 28;
  public static final int EClau = 12;
  public static final int OLI = 27;
  public static final int PRINCIPAL = 33;
  public static final int IGUAL = 25;
  public static final int DClaudator = 16;
  public static final int SINO = 32;
  public static final int PER = 30;
  public static final int BOOL = 21;
  public static final int DIV = 5;
  public static final int MAJOR = 17;
  public static final int SUMA = 2;
  public static final int ASSIGN = 8;
  public static final int FUNCIO = 22;
  public static final int ID = 19;
  public static final int EOF = 0;
  public static final int DClau = 13;
  public static final int error = 1;
  public static final int MUL = 4;
  public static final int BUIT = 24;
  public static final int COMA = 14;
  public static final int EClaudator = 15;
  public static final int MENOR = 18;
  public static final int MOD = 38;
  public static final int RETORNA = 23;
  public static final int ENT = 20;
  public static final int MENTRE = 29;
  public static final int DParen = 7;
  public static final int ENTRADA = 36;
  public static final int SORTIDA = 34;
  public static final int FINAL = 41;
  public static final int BOOLEA = 11;
  public static final int STRING = 40;
  public static final int PUNTICOMA = 9;
  public static final int TEXT = 39;
  public static final int SORTIDALN = 35;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUMA",
  "RESTA",
  "MUL",
  "DIV",
  "EParen",
  "DParen",
  "ASSIGN",
  "PUNTICOMA",
  "ENTER",
  "BOOLEA",
  "EClau",
  "DClau",
  "COMA",
  "EClaudator",
  "DClaudator",
  "MAJOR",
  "MENOR",
  "ID",
  "ENT",
  "BOOL",
  "FUNCIO",
  "RETORNA",
  "BUIT",
  "IGUAL",
  "DIFERENT",
  "OLI",
  "OLO",
  "MENTRE",
  "PER",
  "SI",
  "SINO",
  "PRINCIPAL",
  "SORTIDA",
  "SORTIDALN",
  "ENTRADA",
  "RESERVA",
  "MOD",
  "TEXT",
  "STRING",
  "FINAL"
  };
}

